version: '2'

services:
  nginx:
    restart: always
    image: nginx:1.20.1
    ports:
      - 8000:8000
    volumes:
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/server/static
  wsgiserver:
    build:
      context: .
      dockerfile: ./backend/docker/backend/Dockerfile
    entrypoint: /app/backend/docker/backend/wsgi-entrypoint.sh
    volumes:
      - static_volume:/app/backend/server/static
    expose:
      - 8000
volumes:
  static_volume: {}