# Generated by Django 3.2.6 on 2021-08-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlalgorithmstatus',
            old_name='active',
            new_name='is_active',
        ),
    ]
